# Generated by Django 3.1.2 on 2021-05-16 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
        model_name='subscription',
        name='billing_address',
        ),
        migrations.AddField(
            model_name='subscription',
            name='billing_address',
            field=models.JSONField(default=None),
        ),
        migrations.RemoveField(
        model_name='subscription',
        name='shipping_address',
        ),
        migrations.AddField(
            model_name='subscription',
            name='shipping_address',
            field=models.JSONField(default=None),
        ),
    ]
