# Generated by Django 3.1.2 on 2021-05-16 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_auto_20210516_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='frequency',
            field=models.CharField(choices=[('monthly', 'monthly'), ('weekly', 'weekly')], default='monthly', max_length=32),
        ),
    ]
