# Generated by Django 3.1.2 on 2021-05-16 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_subscription_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='frequency',
            field=models.CharField(choices=[('MONTHLY', 'monthly'), ('WEEKLY', 'weekly')], max_length=255),
        ),
    ]
