# Generated by Django 3.1.2 on 2021-05-16 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_auto_20210516_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='frequency',
            field=models.CharField(choices=[('MONTHLY', 'MONTHLY'), ('WEEKLY', 'WEEKLY')], max_length=255),
        ),
    ]
