# Generated by Django 3.1.2 on 2021-05-19 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_auto_20210516_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='token_customer_id',
            field=models.CharField(default=None, max_length=32),
        ),
    ]
