# Generated by Django 3.1.2 on 2021-05-19 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0131_update_ts_vector_existing_product_name'),
        ('subscriptions', '0007_subscription_next_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='variant_id',
        ),
        migrations.AddField(
            model_name='subscription',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='product.productvariant'),
        ),
    ]
