# Generated by Django 3.1.2 on 2021-05-19 21:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0008_auto_20210519_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='next_order_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
