# Generated by Django 3.1.2 on 2021-05-19 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0047_auto_20200810_1415'),
        ('subscriptions', '0009_auto_20210519_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='billing_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='account.address'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='account.address'),
        ),
    ]
