# Generated by Django 3.1.2 on 2021-05-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0010_auto_20210519_2157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='frequency',
            new_name='frequency_period',
        ),
        migrations.AddField(
            model_name='subscription',
            name='frequency_units',
            field=models.IntegerField(default=1),
        ),
    ]
