# Generated by Django 3.1.2 on 2021-05-19 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0047_auto_20200810_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='company_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='last_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='street_address_2',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
