# Generated by Django 3.1.2 on 2021-06-03 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0048_auto_20210519_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='street_address_2',
            field=models.CharField(blank=True, default='', max_length=256),
            preserve_default=False,
        ),
    ]
